### ISSUE TITLE
Create Object file for ExpandedMovieCard

### ISSUE THREAD

**Issue by B3DAN** [cse110-fa22-group9/Team9Repository#18]
##### What is the objective of this ticket?
Create a JS file to implement a Shadow DOM for ExpandedMovieCard, with an article and styling element.
This object will take in Data:
ShowTitle:
ShowImg:
Reviews:
Review Text:
Num of seasons: 
Current 2D array of shows watched:

##### What are some rabbitholes and risks?

How to pull data for 2D array?

**Comment by OrangeTrashBin** [comment]
added all functions needed. Need support from HTML team
